### ISSUE TITLE
Unexpected HQX results, possibly from the LUT texture

### ISSUE THREAD

**Issue by altmoola** [CrossVR/hqx-shader#1]
I am getting this result after implementing the HQX filter in a MonoGame solution:

![Actual](http://i.stack.imgur.com/VG4Vt.png)

I think it has something to do with the LUT texture that is being loaded, I'm just unsure how to solve it.

This is how the image is configured in the MonoGame pipeline:

![LutConfig](http://i.stack.imgur.com/n4WlY.png)

I've tried the following variations of the LUT texture with no luck:
- Normal
- Normal Rotated 90
- Normal Rotated 180
- Normal Rotated 270
- Horizontal Flip
- Horizontal Flip Rotated 90
- Horizontal Flip Rotated 180
- Horizontal Flip Rotated 270
- Vertical Flip
- Vertical Flip Rotated 90
- Vertical Flip Rotated 180
- Vertical Flip Rotated 270
- Horizontal Flip then Vertical Flip
- Horizontal Flip then Vertical Flip Rotated 90
- Horizontal Flip then Vertical Flip Rotated 180
- Horizontal Flip then Vertical Flip Rotated 270
- Vertical Flip then Horizonal Flip
- Vertical Flip then Horizonal Flip Rotated 90
- Vertical Flip then Horizonal Flip Rotated 180
- Vertical Flip then Horizonal Flip Rotated 270

I've also tried all of these with and without mipmaps. Any ideas as to why this isn't working?

**Comment by CrossVR** [comment]
You need to turn off PremultiplyAlpha.

ResizeToPowerOfTwo is redundant and you don't want to GenerateMipmaps, so turn those off too.

**Comment by altmoola** [comment]
Well, I feel like an idiot. Thanks man, that worked.

**Comment by CrossVR** [comment]
Yeah, it's a bit annoying. I absolutely need to use all 4 channels to store the weights but a lot of imaging libraries pre-multiply the alpha values which messes with the data in the RGB channels.

**Comment by CrossVR** [comment]
Also, would you mind posting a picture of it working? I'm always interested to see the results of applying my shader.

**Comment by altmoola** [comment]
I think it was just one of those things. I was basically trying everything I could think of and was in the middle of figuring out your [LUT generation code](https://github.com/Armada651/hqx-lut-generator) when I saw your response. Yet I didn't try the simplest thing first, testing all options in the pipeline config. Ah well.

Here is a picture of it working, as requested:

![Working](http://i.imgur.com/br9F0T8.png)

Looks great! Thanks again.

**Comment by altmoola** [comment]
Here is the same scene with xBR (squared variation) for comparison:

![XBR](http://i.imgur.com/aCs8NSX.png)

Biggest complaint with the XBR one is that it really washes out the detail of the character sprite. I think HQX looks much better for him.

**Comment by greyp** [comment]
Hi guys, is there any chance that I get access to the HQX shader or xBR shader that you are using for MonoGame? I've been trying for a while to get xBR working in my game but got no success so far. I also tried translating [Hyllian's xbr-lv2 shader](https://github.com/libretro/common-shaders/blob/master/xbr/shaders/xbr-lv2.cg) to HLSL, but the end result looked similar to the first image in this thread... :(

**Comment by CrossVR** [comment]
@greyp There's a thread about it here if you're still looking for it: http://libretro.com/forums/showthread.php?t=4162
